### PR TITLE
Try out reviewable

### PR DESCRIPTION
**Pull request by mkmik**
[Review on Reviewable](https://reviewable.io/reviews/cesanta/gerrit-test/3)

### CODE REVIEW

**Comment by mkmik** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/gerrit-test/3)

---

<sup>**[test.md, line 2 [r1]](https://reviewable.io:443/reviews/cesanta/gerrit-test/3#-Jk_NuW27__lBetvjb2k)** ([raw file](https://github.com/cesanta/gerrit-test/blob/f34f1ebd1b247e1c3d480906cf8d3de919903307/test.md#L2)):</sup>
please use a real URL

---

**Comment by mkmik** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/gerrit-test/3)

---

<sup>**[test.md, line 2 [r1]](https://reviewable.io:443/reviews/cesanta/gerrit-test/3#-Jk_NuW27__lBetvjb2k)** ([raw file](https://github.com/cesanta/gerrit-test/blob/f34f1ebd1b247e1c3d480906cf8d3de919903307/test.md#L2)):</sup>
Done.

---

**Comment by cpq** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/gerrit-test/3)

---

<sup>**[test.md, line 2 [r1]](https://reviewable.io:443/reviews/cesanta/gerrit-test/3#-Jk_NuW27__lBetvjb2k)** ([raw file](https://github.com/cesanta/gerrit-test/blob/f34f1ebd1b247e1c3d480906cf8d3de919903307/test.md#L2)):</sup>
Can I see the history?

---

**Comment by mkmik** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/gerrit-test/3)

---

<sup>**[test.md, line 2 [r1]](https://reviewable.io:443/reviews/cesanta/gerrit-test/3#-Jk_NuW27__lBetvjb2k)** ([raw file](https://github.com/cesanta/gerrit-test/blob/f34f1ebd1b247e1c3d480906cf8d3de919903307/test.md#L2)):</sup>
Yes,  just click around in the columns ("bottom", "r1", "r2") to set start and end point of the diff view

---

**Comment by mkmik** [comment]
obsolete

**Pull request closed without merging**
